version: '3'

services:
    web:
        image: nginx:1.16.1
        container_name: nginx1.6
        restart: on-failure
        ports:
            - "5000:80"
        volumes:
            - ./www:/var/www
            - ./nginx1.6/site.conf:/etc/nginx/conf.d/site.conf
        working_dir: /var/www
        networks:
          backend:
            ipv4_address: 172.16.238.10

    php:
        build:
            context: ./php/8.0.6
            dockerfile: Dockerfile
        container_name: php8.0.6
        volumes:
            - ./www:/var/www
        networks:
          backend:
            ipv4_address: 172.16.238.11

networks:
    backend:
        ipam:
            driver: default
            config:
                - subnet: "172.16.238.0/24"
